let products = [
    {
        id:1,
        name:"apple",
        price:500
    },{
        id:2,
        name:"apricot",
        price:600
    },{
        id:3,
        name:"avocado",
        price:700
    },{
        id:4,
        name:"banana",
        price:800
    },{
        id:5,
        name:"bilberry",
        price:900
    },{
        id:6,
        name:"blackberry",
        price:1000
    },{
        id:7,
        name:"blackcurrant",
        price:400
    },{
        id:8,
        name:"cherry",
        price:1200
    },{
        id:9,
        name:"orange",
        price:700
    },{
        id:10,
        name:"watermelon",
        price:1500
    },{
        id:11,
        name:"apstrawberryple",
        price:2500
    }
]